import { Jost } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Providers from "@/redux/app/provider";

const jost = Jost({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jost.className} bg-[#161616] text-white`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
